#!/usr/bin/env python3
"""Build firmware/rom_images.c for the MHB 2616 firmware.

Three ways in:

  --monitor FILE   one 8192-byte image -- the shape a PMD 85-3 monitor dump
                   (e.g. MAME's pmd85-3.bin) comes in.  Split across the four
                   banks in address order: bank 0 = 0x0000, bank 3 = 0x1800.

  chip dumps       up to four 2048-byte files, assigned to banks 0,1,2,...
                   in the order given, or explicitly with --bank (once per
                   dump, in order).  Banks not covered are marked absent:
                   EXT-mode firmware will not drive the bus for them, which
                   is what lets a partial set coexist with real chips.

  --selftest       ignore the inputs and emit the self-identifying pattern
                   for all four banks.  See selftest.py.

  --module FILE    a ROM module image -- a .rmm, or any file up to 16 KB --
                   for MHB_BANK_SOURCE=MODULE.  Split across EIGHT 2 KB
                   banks, because the module's window is 16 KB and not 8,
                   and banks past the end of the file are marked absent so
                   the board leaves them reading 0xFF exactly as an
                   unpopulated module socket does.

    ./gen_rom_images.py -o ../firmware/rom_images.c --monitor pmd85-3.bin
    ./gen_rom_images.py -o ../firmware/rom_images.c --bank 2 mz3_dump.bin
    ./gen_rom_images.py -o ../firmware/rom_images.c --module basic3.rmm
"""

import argparse
import sys
from pathlib import Path

import selftest

BANKS = 4
BANK_SIZE = 2048

# The module window: A0-A10 on the socket, A11-A13 from the 7442's inputs.
# A14 is the read strobe and A15 parks the decoder, so 16 KB is the ceiling
# this card can express -- see docs/ROM-module.md.
MODULE_BANKS = 8


def emit(output: Path, name: str, banks: list, present: int, note: str,
         window: str = "monitor") -> None:
    total = len(banks)
    out = [f"// Generated by tools/gen_rom_images.py -- do not edit.",
           f"// {note}", "", '#include "rom_images.h"', ""]
    # The bank count is a property of the image and of the firmware mode, and
    # they must agree.  Asserting it here turns "module image, monitor build"
    # into a compile error naming both numbers, instead of a board that serves
    # the first quarter of the window and 0xFF for the rest.
    out.append(f"_Static_assert(MHB_BANKS == {total},")
    out.append(f'               "this image has {total} banks; the firmware '
               f'was built for a different count");')
    out.append("")
    out.append(f'const char *mhb_image_name = "{name}";')
    out.append(f"const uint8_t mhb_bank_present = 0x{present:02X};")
    out.append("")
    out.append(f"const uint8_t mhb_banks[MHB_BANKS][MHB_BANK_SIZE] = {{")
    for b in range(total):
        data = banks[b] if banks[b] is not None else bytes([0xFF]) * BANK_SIZE
        tag = "" if banks[b] is not None else "  (absent: filler, never driven)"
        out.append(f"    // bank {b}: {window} 0x{b * BANK_SIZE:04X}-"
                   f"0x{(b + 1) * BANK_SIZE - 1:04X}{tag}")
        out.append("    {")
        for j in range(0, BANK_SIZE, 16):
            row = ", ".join(f"0x{x:02X}" for x in data[j:j + 16])
            out.append(f"        {row},")
        out.append("    },")
    out.append("};")
    out.append("")
    output.write_text("\n".join(out))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dumps", nargs="*", type=Path,
                    help="2048-byte chip dumps, banks 0,1,2,... in order")
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--monitor", type=Path,
                    help="one 8192-byte monitor image split across all banks")
    ap.add_argument("--bank", type=int, action="append", default=[],
                    help="bank number for each dump, once per dump, in order")
    ap.add_argument("--selftest", action="store_true",
                    help="emit the self-identifying pattern for all banks")
    ap.add_argument("--module", type=Path,
                    help="a ROM module image (<= 16 KB) across eight banks")
    args = ap.parse_args()

    modes = sum([bool(args.monitor), bool(args.dumps), args.selftest,
                 bool(args.module)])
    if modes != 1:
        print("error: give exactly one of --monitor, --module, --selftest, "
              "or chip dumps", file=sys.stderr)
        return 1

    if args.module:
        raw = args.module.read_bytes()
        if not raw or len(raw) > MODULE_BANKS * BANK_SIZE:
            print(f"error: {args.module.name} is {len(raw)} bytes; a module "
                  f"image must be 1..{MODULE_BANKS * BANK_SIZE}", file=sys.stderr)
            return 1
        banks, present = [], 0
        for b in range(MODULE_BANKS):
            chunk = raw[b * BANK_SIZE:(b + 1) * BANK_SIZE]
            if chunk:
                # A short final bank is real data padded to the window, not an
                # absent one: the machine may legitimately read past the image.
                banks.append(chunk + bytes([0xFF]) * (BANK_SIZE - len(chunk)))
                present |= 1 << b
            else:
                banks.append(None)
        emit(args.output, args.module.stem, banks, present,
             f"{len(raw)}-byte ROM module image from {args.module.name}.",
             window="module")
        absent = [str(b) for b in range(MODULE_BANKS) if not (present >> b) & 1]
        note = f", banks {','.join(absent)} absent (read 0xFF)" if absent else ""
        print(f"wrote {args.output}: {args.module.name} across "
              f"{bin(present).count('1')} of {MODULE_BANKS} module banks{note}")
        return 0

    if args.selftest:
        banks = [selftest.image(b) for b in range(BANKS)]
        emit(args.output, "selftest", banks, 0x0F,
             "Self-test patterns, not ROM contents; see tools/selftest.py.")
        print(f"wrote {args.output}: self-test pattern, 4 banks")
        return 0

    if args.monitor:
        raw = args.monitor.read_bytes()
        if len(raw) != BANKS * BANK_SIZE:
            print(f"error: {args.monitor.name} is {len(raw)} bytes, "
                  f"expected {BANKS * BANK_SIZE}", file=sys.stderr)
            return 1
        banks = [raw[b * BANK_SIZE:(b + 1) * BANK_SIZE] for b in range(BANKS)]
        emit(args.output, args.monitor.stem, banks, 0x0F,
             f"8 KB monitor image from {args.monitor.name}.")
        print(f"wrote {args.output}: {args.monitor.name} across 4 banks")
        return 0

    if len(args.dumps) > BANKS:
        print(f"error: at most {BANKS} dumps", file=sys.stderr)
        return 1
    if args.bank and len(args.bank) != len(args.dumps):
        print("error: --bank must be given once per dump, or not at all",
              file=sys.stderr)
        return 1

    banks = [None] * BANKS
    present = 0
    for i, path in enumerate(args.dumps):
        raw = path.read_bytes()
        if len(raw) != BANK_SIZE:
            print(f"error: {path.name} is {len(raw)} bytes, expected {BANK_SIZE}",
                  file=sys.stderr)
            return 1
        b = (args.bank[i] if args.bank else i) & 3
        if banks[b] is not None:
            print(f"error: two dumps claim bank {b}", file=sys.stderr)
            return 1
        banks[b] = raw
        present |= 1 << b

    name = "+".join(p.stem for p in args.dumps)
    emit(args.output, name, banks, present,
         f"Chip dumps: {', '.join(p.name for p in args.dumps)}.")
    absent = [str(b) for b in range(BANKS) if not (present >> b) & 1]
    note = f", banks {','.join(absent)} absent" if absent else ""
    print(f"wrote {args.output}: {len(args.dumps)} bank(s){note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
