#!/usr/bin/env python3
"""Build firmware/rom_images.c for the MHB 2616 firmware.

Three ways in:

  --monitor FILE   one 8192-byte image -- the shape a PMD 85-3 monitor dump
                   (e.g. MAME's pmd85-3.bin) comes in.  Split across the four
                   banks in address order: bank 0 = 0x0000, bank 3 = 0x1800.

  chip dumps       up to four 2048-byte files, assigned to banks 0,1,2,...
                   in the order given, or explicitly with --bank (once per
                   dump, in order).  Banks not covered are marked absent:
                   EXT-mode firmware will not drive the bus for them, which
                   is what lets a partial set coexist with real chips.

  --selftest       ignore the inputs and emit the self-identifying pattern
                   for all four banks.  See selftest.py.

    ./gen_rom_images.py -o ../firmware/rom_images.c --monitor pmd85-3.bin
    ./gen_rom_images.py -o ../firmware/rom_images.c --bank 2 mz3_dump.bin
"""

import argparse
import sys
from pathlib import Path

import selftest

BANKS = 4
BANK_SIZE = 2048


def emit(output: Path, name: str, banks: list, present: int, note: str) -> None:
    out = [f"// Generated by tools/gen_rom_images.py -- do not edit.",
           f"// {note}", "", '#include "rom_images.h"', ""]
    out.append(f'const char *mhb_image_name = "{name}";')
    out.append(f"const uint8_t mhb_bank_present = 0x{present:02X};")
    out.append("")
    out.append(f"const uint8_t mhb_banks[MHB_BANKS][MHB_BANK_SIZE] = {{")
    for b in range(BANKS):
        data = banks[b] if banks[b] is not None else bytes([0xFF]) * BANK_SIZE
        tag = "" if banks[b] is not None else "  (absent: filler, never driven in EXT)"
        out.append(f"    // bank {b}: monitor 0x{b * BANK_SIZE:04X}-"
                   f"0x{(b + 1) * BANK_SIZE - 1:04X}{tag}")
        out.append("    {")
        for j in range(0, BANK_SIZE, 16):
            row = ", ".join(f"0x{x:02X}" for x in data[j:j + 16])
            out.append(f"        {row},")
        out.append("    },")
    out.append("};")
    out.append("")
    output.write_text("\n".join(out))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dumps", nargs="*", type=Path,
                    help="2048-byte chip dumps, banks 0,1,2,... in order")
    ap.add_argument("-o", "--output", type=Path, required=True)
    ap.add_argument("--monitor", type=Path,
                    help="one 8192-byte monitor image split across all banks")
    ap.add_argument("--bank", type=int, action="append", default=[],
                    help="bank number for each dump, once per dump, in order")
    ap.add_argument("--selftest", action="store_true",
                    help="emit the self-identifying pattern for all banks")
    args = ap.parse_args()

    modes = sum([bool(args.monitor), bool(args.dumps), args.selftest])
    if modes != 1:
        print("error: give exactly one of --monitor, --selftest, or chip dumps",
              file=sys.stderr)
        return 1

    if args.selftest:
        banks = [selftest.image(b) for b in range(BANKS)]
        emit(args.output, "selftest", banks, 0x0F,
             "Self-test patterns, not ROM contents; see tools/selftest.py.")
        print(f"wrote {args.output}: self-test pattern, 4 banks")
        return 0

    if args.monitor:
        raw = args.monitor.read_bytes()
        if len(raw) != BANKS * BANK_SIZE:
            print(f"error: {args.monitor.name} is {len(raw)} bytes, "
                  f"expected {BANKS * BANK_SIZE}", file=sys.stderr)
            return 1
        banks = [raw[b * BANK_SIZE:(b + 1) * BANK_SIZE] for b in range(BANKS)]
        emit(args.output, args.monitor.stem, banks, 0x0F,
             f"8 KB monitor image from {args.monitor.name}.")
        print(f"wrote {args.output}: {args.monitor.name} across 4 banks")
        return 0

    if len(args.dumps) > BANKS:
        print(f"error: at most {BANKS} dumps", file=sys.stderr)
        return 1
    if args.bank and len(args.bank) != len(args.dumps):
        print("error: --bank must be given once per dump, or not at all",
              file=sys.stderr)
        return 1

    banks = [None] * BANKS
    present = 0
    for i, path in enumerate(args.dumps):
        raw = path.read_bytes()
        if len(raw) != BANK_SIZE:
            print(f"error: {path.name} is {len(raw)} bytes, expected {BANK_SIZE}",
                  file=sys.stderr)
            return 1
        b = (args.bank[i] if args.bank else i) & 3
        if banks[b] is not None:
            print(f"error: two dumps claim bank {b}", file=sys.stderr)
            return 1
        banks[b] = raw
        present |= 1 << b

    name = "+".join(p.stem for p in args.dumps)
    emit(args.output, name, banks, present,
         f"Chip dumps: {', '.join(p.name for p in args.dumps)}.")
    absent = [str(b) for b in range(BANKS) if not (present >> b) & 1]
    note = f", banks {','.join(absent)} absent" if absent else ""
    print(f"wrote {args.output}: {len(args.dumps)} bank(s){note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
